#!/bin/bash
set -e

psql -U postgres -d postgres <<EOF
-- Create application database and user
CREATE DATABASE IF NOT EXISTS "${POSTGRES_APP_DB}";
CREATE USER IF NOT EXISTS ${POSTGRES_APP_USER} WITH ENCRYPTED PASSWORD '${POSTGRES_APP_PASSWORD}';
ALTER DATABASE "${POSTGRES_APP_DB}" OWNER TO ${POSTGRES_APP_USER};

-- Create n8n database and user
CREATE DATABASE IF NOT EXISTS "${POSTGRES_N8N_DB}";
CREATE USER IF NOT EXISTS ${POSTGRES_N8N_USER} WITH ENCRYPTED PASSWORD '${POSTGRES_N8N_PASSWORD}';
ALTER DATABASE "${POSTGRES_N8N_DB}" OWNER TO ${POSTGRES_N8N_USER};
EOF
